import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/context/ChatContext";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <main>{children}</main>
          <Toaster position="top-right" duration={2000}/>
        </AuthProvider>
      </body>
    </html>
  );
}
